### PR TITLE
More metadata and album art in mp3 file

### PR DESCRIPTION
**Pull request by xabixab**
This adds "Album" metadata "date" metadata and it adds the album art inside the mp3 file.

### CODE REVIEW

**Comment by regisb** [comment]
@xabixab Thanks for your pull request! I believe that the feature you implemented is a very useful one and we should add it to spotify-onthego. However, if possible I would like to add this feature without the extra dependency. Is there any way to add the album art to the result mp3 without eyeD3-pip? For instance, with `avconv?

**Comment by regisb** [comment]
@xabixab Thanks for your pull request! I believe that the feature you implemented is a very useful one and we should add it to spotify-onthego. However, if possible I would like to add this feature without the extra dependency. Is there any way to add the album art to the result mp3 without eyeD3-pip? For instance, with `avconv`?

**Comment by xabixab** [comment]
Sincerely, I do not know. I have done with eyeD3 because is the easiest way for me. Now I am developing a feature that lets you create .m3u file with the songs inside the downloaded playlist, but it uses extra dependences. Do you think I should do a pull request?

I am new at Github and I don't know python well. Sorry about my poor English level.

**Comment by regisb** [comment]
@xabixab No worries, you're doing good :) I see that your pull request changes multiple things:

1. Add album art metadata: this is a great feature and we should implement it, if possible without adding an extra dependency
2. Add album and year metadata: requires an extra call to the spotify API and I feel like it's a feature that is less necessary (but perhaps I'm mistaken?).
3. Fix the artist and track names: this is superfluous because we don't need to remove "[", "]", "@" characters: such characters are allowed on all OS, right? To make sure windows paths are supported, we could simply change `filename = filename.replace('/', ' ')` into `filename = filename.replace('/', ' ').replace('/', ' ')`.

**Comment by xabixab** [comment]
About the album and year metadata, I think is useful because there are players that organizes the songs in albums looking on that metadata. The year could be less useful.

I do not remember why I filter the data. I think it was because it didn't skip the songs that were already downloaded and contain those characters.

**Comment by regisb** [comment]
@xabixab : I have finally decided that to merge your PR, because the new feature is worth the extra dependency. Note that I have squashed and reworded your commits, and have added other commits. In particular:

- I have switched from eyed3-pip to eyed3, which seems more mainstream. The corresponding requirement has been added to requirements.txt.
- The filename filter was removed.
- Your author changes to setup.py have not been integrated. I'm sure you understand :)
- Since there was a lot of track-related info, a Track class was created.

You are welcome to create a new pull request to create playlist files. But I'm not sure this feature would be very useful. It seems to me that a simple `ls *.mp3 > playlist.m3u` should be enough to create a playlist file.

Thanks for your contribution!

**Comment by xabixab** [comment]
I am new on github, sorry about setup.py
I didn't want to include that in pull request.

**Comment by regisb** [comment]
No worries :)

**Pull request closed without merging**
